// Example: generator hooks (PR3).
//
// This is a self-contained runnable config: it picks up the bundled
// `petstore.json` fixture, registers a banner-and-timestamp plugin via
// the `plugins` field, and writes `api.ts` next to this file.
//
// Demonstrates two of the three hook slots in a single plugin:
//   - afterFormat: prepend a license header + generation timestamp
//     banner onto the prettier-formatted source.
//   - writeFile: log the output path AND still call the built-in
//     writer so the file ends up on disk.
//
// (The `beforeEmit` slot is exercised in `__tests__/generator-hook.test.ts`
// — we leave it out of this runnable example so the config stays
// readable without pulling in the TS factory.)
//
// Run from repo root:
//   pnpm exec tsdown
//   node bin/cli.cjs \
//     --config example/plugins/banner-and-timestamp/apicodegen.config.mjs \
//     example/plugins/banner-and-timestamp/petstore.json
//
// Then `cat example/plugins/banner-and-timestamp/api.ts` — the file
// should start with the SPDX banner comment.

import path from 'node:path';
import { fileURLToPath } from 'node:url';
// Import from the local built `npm/` output so the example can run
// against the just-built CLI (`node bin/cli.cjs ...`). Importing from
// `../../../src/...` would only work when running via a TS-aware runner.
import { Generator, definePlugin } from '../../../npm/index.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const header = `/**
 * Copyright (c) ${new Date().getFullYear()} Acme Corp.
 * SPDX-License-Identifier: MIT
 *
 * AUTO-GENERATED by @moccona/apicodegen — do not edit by hand.
 * Generated at: ${new Date().toISOString()}
 */
`;

/** @type {import('../../../npm/index.mjs').Plugin} */
const bannerPlugin = definePlugin({
	name: 'example-banner-and-timestamp',
	version: '0.1.0',

	// (1) After prettier — prepend the header.
	afterFormat: ({ code }) => `${header}${code}`,

	// (2) Replace the writer. We log and then delegate to the built-in
	// `Generator.write` so a future plugin that overrides `writeFile`
	// before us still benefits from this side-effect.
	writeFile: async (ctx) => {
		// biome-ignore: intentional console.log in example
		console.log(
			`[example] writing ${ctx.code.length} bytes to ${path.relative(__dirname, ctx.output)}`
		);
		await Generator.write(ctx.code, ctx.output);
	},
});

export default {
	spec: path.join(__dirname, 'petstore.json'),
	output: path.join(__dirname, 'api.ts'),
	plugins: [bannerPlugin],
};
