// End-to-end tests for the generator hook pipeline (PR3).
//
// Coverage:
//   - beforeEmit hook can mutate Statement[] before the printer runs.
//   - afterFormat hook can post-process the formatted source string.
//   - writeFile hook replaces the default file writer.
//   - Hooks run in declaration order; first writeFile wins.
import fs from 'node:fs/promises';
import path from 'node:path';
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import type { Statement } from 'typescript';
import { factory as t } from 'typescript';
import { codeGen } from '../src/openapi/index.js';
import { definePlugin } from '../src/core/plugin.js';
import { Generator } from '../src/core/generator/index.js';

function tinySpec() {
	return {
		openapi: '3.0.0',
		info: { title: 'Hook Demo', version: '1.0.0' },
		paths: {
			'/demo/ping': {
				get: {
					operationId: 'demoPing',
					summary: 'ping',
					responses: {
						'200': {
							content: {
								'application/json': { schema: { type: 'string' } },
							},
						},
					},
				},
			},
		},
	};
}

async function writeSpec(dir: string, name = 'spec.json'): Promise<string> {
	const p = path.join(dir, name);
	await fs.writeFile(p, JSON.stringify(tinySpec()));
	return p;
}

describe('generator hooks (PR3)', () => {
	const tmpRoot = path.join(
		process.cwd(),
		`__tests__/__tmp_generator_hook_${process.pid}`
	);

	beforeEach(async () => {
		await fs.mkdir(tmpRoot, { recursive: true });
	});

	afterEach(async () => {
		await fs.rm(tmpRoot, { recursive: true, force: true });
	});

	it('runs beforeEmit hooks in order and feeds the output to the printer', async () => {
		const specPath = await writeSpec(tmpRoot);

		let calls = 0;
		const plugin = definePlugin({
			name: 'add-trailing-comment',
			// NOTE: destructure the hook context. A bare `beforeEmit(statements)`
			// would NOT work — the hook receives a `ctx` object whose first
			// field is `initOptions`, not `statements`. The destructure pulls
			// `statements` out explicitly.
			beforeEmit: ({ statements }) => {
				calls += 1;
				// Append a `// generated by hook` comment statement.
				return [
					...statements,
					t.createExpressionStatement(
						t.createStringLiteral('// generated by hook')
					),
				];
			},
		});

		const result = await codeGen({
			docURL: specPath,
			output: '',
			plugins: [plugin],
		});

		expect(calls).toBe(1);
		expect(result.code).toContain('// generated by hook');
		expect(result.code).toContain('export async function demoPing');
	});

	it('chains multiple beforeEmit hooks: later hook sees earlier output', async () => {
		const specPath = await writeSpec(tmpRoot);
		const order: string[] = [];

		await codeGen({
			docURL: specPath,
			output: '',
			plugins: [
				definePlugin({
					name: 'first',
					beforeEmit: ({ statements }) => {
						order.push('first');
						return [
							...statements,
							t.createExpressionStatement(t.createStringLiteral('// first')),
						];
					},
				}),
				definePlugin({
					name: 'second',
					beforeEmit: ({ statements }) => {
						order.push('second');
						return [
							...statements,
							t.createExpressionStatement(t.createStringLiteral('// second')),
						];
					},
				}),
			],
		});

		expect(order).toEqual(['first', 'second']);
	});

	it('runs afterFormat hooks and feeds the output downstream', async () => {
		const specPath = await writeSpec(tmpRoot);
		const plugin = definePlugin({
			name: 'append-banner',
			afterFormat(code) {
				return `/* BANNER */\n${code}`;
			},
		});

		const result = await codeGen({
			docURL: specPath,
			output: '',
			plugins: [plugin],
		});

		expect(result.code.startsWith('/* BANNER */')).toBe(true);
	});

	it('runs an async hook and awaits it', async () => {
		const specPath = await writeSpec(tmpRoot);
		const plugin = definePlugin({
			name: 'async-banner',
			async afterFormat(code) {
				await new Promise((r) => setTimeout(r, 1));
				return `// async\n${code}`;
			},
		});

		const result = await codeGen({
			docURL: specPath,
			output: '',
			plugins: [plugin],
		});

		expect(result.code.startsWith('// async')).toBe(true);
	});

	it('uses writeFile hook instead of Generator.write()', async () => {
		const specPath = await writeSpec(tmpRoot);
		const outputPath = path.join(tmpRoot, 'custom-output.ts');
		const written: string[] = [];

		const plugin = definePlugin({
			name: 'capture-and-write',
			async writeFile({ code, output }) {
				written.push(output);
				await fs.writeFile(output, `// captured\n${code}`);
			},
		});

		await codeGen({
			docURL: specPath,
			output: outputPath,
			plugins: [plugin],
		});

		const fileContents = await fs.readFile(outputPath, 'utf8');
		expect(written).toEqual([outputPath]);
		expect(fileContents.startsWith('// captured')).toBe(true);
		expect(fileContents).toContain('export async function demoPing');
	});

	it('first writeFile hook wins; later ones are skipped', async () => {
		const specPath = await writeSpec(tmpRoot);
		const outputPath = path.join(tmpRoot, 'first-wins.ts');
		const fired: string[] = [];

		await codeGen({
			docURL: specPath,
			output: outputPath,
			plugins: [
				definePlugin({
					name: 'first',
					async writeFile({ output, code }) {
						fired.push('first');
						await fs.writeFile(output, `// first\n${code}`);
					},
				}),
				definePlugin({
					name: 'second',
					async writeFile({ output, code }) {
						fired.push('second');
						await fs.writeFile(output, `// second\n${code}`);
					},
				}),
			],
		});

		expect(fired).toEqual(['first']);
		const fileContents = await fs.readFile(outputPath, 'utf8');
		expect(fileContents.startsWith('// first')).toBe(true);
	});

	it('no hooks => behavior identical to baseline', async () => {
		const specPath = await writeSpec(tmpRoot);
		const result = await codeGen({
			docURL: specPath,
			output: '',
		});

		expect(result.code).toContain('export async function demoPing');
		expect(result.code).toContain('fetch(');
	});

	it('passes useful context to beforeEmit (initOptions, schema, adapter, output)', async () => {
		const specPath = await writeSpec(tmpRoot);
		let captured: unknown;

		await codeGen({
			docURL: specPath,
			output: '',
			baseURL: 'https://example.com',
			plugins: [
				definePlugin({
					name: 'capture',
					beforeEmit: ({ statements }) => {
						captured = { statements };
						return statements as unknown as import('typescript').Statement[];
					},
				}),
			],
		});

		expect(captured).toBeDefined();
		const { statements } = captured as { statements: Statement[] };
		expect(Array.isArray(statements)).toBe(true);
		expect(statements.length).toBeGreaterThan(0);
	});

	it('ctx.initOptions is a deep-cloned snapshot — mutations do not leak', async () => {
		const specPath = await writeSpec(tmpRoot);
		const plugin = definePlugin({
			name: 'snapshot-check',
			beforeEmit: ({ initOptions }) => {
				// `initOptions` should be frozen (and thus read-only).
				expect(() => {
					(initOptions as { docURL: string }).docURL = 'mutated';
				}).toThrow();
				return [];
			},
		});
		await codeGen({ docURL: specPath, output: '', plugins: [plugin] });
	});

	it('ctx.schema is a deep-cloned snapshot — mutations do not leak', async () => {
		const specPath = await writeSpec(tmpRoot);
		const plugin = definePlugin({
			name: 'snapshot-check',
			beforeEmit: ({ schema }) => {
				// `schema.apis` is a plain object/array, so it must be frozen.
				const apis = schema.apis as Record<string, unknown>;
				expect(() => {
					apis['/injected'] = [];
				}).toThrow();
				return [];
			},
		});
		await codeGen({ docURL: specPath, output: '', plugins: [plugin] });
	});

	it('ctx.adapter is shallow-frozen — methods remain callable', async () => {
		const specPath = await writeSpec(tmpRoot);
		const plugin = definePlugin({
			name: 'snapshot-check',
			beforeEmit: ({ adapter }) => {
				// Cannot reassign fields.
				expect(() => {
					(adapter as { name: string }).name = 'mutated';
				}).toThrow();
				// Method `name` getter still works.
				expect(typeof adapter.name).toBe('string');
				return [];
			},
		});
		await codeGen({ docURL: specPath, output: '', plugins: [plugin] });
	});

	it('afterFormat ctx.code and ctx.statements are read-only views', async () => {
		const specPath = await writeSpec(tmpRoot);
		const plugin = definePlugin({
			name: 'snapshot-check',
			afterFormat: ({ code, statements }) => {
				// `code` is a primitive string — naturally immutable.
				expect(typeof code).toBe('string');
				// `statements` array is frozen — push should throw.
				expect(() => {
					(statements as unknown as Statement[]).push({} as Statement);
				}).toThrow();
				return code;
			},
		});
		await codeGen({ docURL: specPath, output: '', plugins: [plugin] });
	});

	it('writeFile ctx is also frozen', async () => {
		const specPath = await writeSpec(tmpRoot);
		const outputPath = path.join(tmpRoot, 'frozen-write.ts');
		const plugin = definePlugin({
			name: 'snapshot-check',
			writeFile: ({ code, output, initOptions }) => {
				expect(() => {
					(initOptions as { docURL: string }).docURL = 'mutated';
				}).toThrow();
				// `output` is a string — already immutable.
				expect(output).toBe(outputPath);
				return fs.writeFile(output, code);
			},
		});
		await codeGen({ docURL: specPath, output: outputPath, plugins: [plugin] });
	});

	// ----- Multi-file writeFile (PR4 extension) --------------------------

	it('writeFile returning Record<path, code> writes multiple files', async () => {
		const specPath = await writeSpec(tmpRoot);
		const apiPath = path.join(tmpRoot, 'split', 'api.ts');
		const typesPath = path.join(tmpRoot, 'split', 'types.ts');
		const schemasPath = path.join(tmpRoot, 'split', 'schemas.ts');

		const plugin = definePlugin({
			name: 'multi-file-splitter',
			writeFile: ({ code }) => ({
				[apiPath]: `// API\n${code}`,
				[typesPath]: '// TYPES\nexport type Marker = "split";\n',
				[schemasPath]: '// SCHEMAS\nexport {};\n',
			}),
		});

		await codeGen({
			docURL: specPath,
			output: apiPath,
			plugins: [plugin],
		});

		const apiContents = await fs.readFile(apiPath, 'utf8');
		const typesContents = await fs.readFile(typesPath, 'utf8');
		const schemasContents = await fs.readFile(schemasPath, 'utf8');

		expect(apiContents.startsWith('// API')).toBe(true);
		expect(apiContents).toContain('export async function');
		expect(typesContents).toContain('Marker');
		expect(schemasContents).toContain('SCHEMAS');
	});

	it('writeFile returning void does NOT fall through to built-in writer', async () => {
		const specPath = await writeSpec(tmpRoot);
		const outputPath = path.join(tmpRoot, 'no-fallthrough.ts');

		const plugin = definePlugin({
			name: 'writes-nothing-extra',
			async writeFile() {
				// Returns void on purpose — must NOT trigger the built-in
				// writer after this hook returns, otherwise we'd get a
				// double-write.
			},
		});

		await codeGen({
			docURL: specPath,
			output: outputPath,
			plugins: [plugin],
		});

		// The file should NOT exist — the hook took ownership and wrote
		// nothing. If the framework fell through to Generator.write, the
		// file would now contain the formatted source.
		await expect(fs.access(outputPath)).rejects.toThrow();
	});

	it('writeFile may call Generator.write itself and return void', async () => {
		const specPath = await writeSpec(tmpRoot);
		const outputPath = path.join(tmpRoot, 'self-write.ts');

		const plugin = definePlugin({
			name: 'self-write-then-void',
			async writeFile({ code }) {
				await Generator.write(`// self-write\n${code}`, outputPath);
				// Returning void signals "I handled it, don't fall through".
			},
		});

		await codeGen({
			docURL: specPath,
			output: outputPath,
			plugins: [plugin],
		});

		const contents = await fs.readFile(outputPath, 'utf8');
		expect(contents.startsWith('// self-write')).toBe(true);
	});

	it('Generator.writeMany writes each entry independently', async () => {
		const a = path.join(tmpRoot, 'many-a.ts');
		const b = path.join(tmpRoot, 'many-b.ts');
		await Generator.writeMany({ [a]: 'A', [b]: 'B' });
		expect(await fs.readFile(a, 'utf8')).toBe('A');
		expect(await fs.readFile(b, 'utf8')).toBe('B');
	});
});
